##前端项目发送请求都带上 api 前缀
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://kedamall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: coupon_route
          uri: lb://kedamall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://kedamall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware_route
          uri: lb://kedamall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://kedamall-thrid-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
              ##重写
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: kedamall_host_route
          uri: lb://kedamall-product
          predicates:
            - Host=kedamall.com,item.kedamall.com
        - id: kedamall_search_route
          uri: lb://kedamall-search
          predicates:
            - Host=search.kedamall.com
        - id: kedamall_auth_route
          uri: lb://kedamall-auth-server
          predicates:
            - Host=auth.kedamall.com
        - id: kedamall_cart_route
          uri: lb://kedamall-cart
          predicates:
            - Host=cart.kedamall.com
        - id: kedamall_order_route
          uri: lb://kedamall-order
          predicates:
            - Host=order.kedamall.com
        - id: kedamall_member_route
          uri: lb://kedamall-member
          predicates:
            - Host=member.kedamall.com
        - id: kedamall_seckill_route
          uri: lb://kedamall-seckill
          predicates:
            - Host=seckill.kedamall.com
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
