spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GAZUbcXaQ7w812Ujaqr
      secret-key: 7hwlOA52Wx6JeJjW9jzPESYeMgD6qm
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: kedamall
  application:
    name: kedamall-thrid-party


server:
  port: 30000

