spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GAZUbcXaQ7w812Ujaqr
      secret-key: 7hwlOA52Wx6JeJjW9jzPESYeMgD6qm
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: kedamall
      sms:
        host: https://feginesms.market.alicloudapi.com
        path: /codeNotice
        skin: 1
        sign: 1
        appcode: 506ce3d9b051423e9de750128d577eaf

  application:
    name: kedamall-thrid-party


server:
  port: 30000

